apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set-echo-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["endpoints"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: set-echo-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: set-echo-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: set-echo-cluster-role
  apiGroup: rbac.authorization.k8s.io
